(function(g){var window=this;var I6=function(a,b){return g.aa[a]=b},Tua=function(a,b){var c=new g.BI;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.G=a.G;c.F=a.F;c.I=a.I;c.g=b;return c},J6=function(a){return a.g?a.g.languageCode:a.o},K6=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.CI(a),kind:a.B,name:a.C,id:a.Ba,is_servable:a.N,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},L6=function(a){if(!Uua.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Vua,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},Wua=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},Xua=function(a){for(var b in a)delete a[b]},M6=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.BJ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.o=k},N6=function(a,b,c,d,e){g.BJ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},P6=function(a){a=void 0===a?{}:a;
var b="_"+O6++;return new N6(0,0x8000000000000,0,b,a)},S6=function(a,b,c,d,e,f){var k={};
g.Ba(k,b);g.Ba(k,a.params);g.Ba(k,c);var l={};g.Ba(l,b.rb);a.params.rb&&g.Ba(l,a.params.rb);g.Ba(l,c.rb);k.rb=l;g.Y.call(this,{H:"div",M:"caption-window",P:{id:"caption-window-"+a.id,dir:k.Nj==Q6.Bp?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},K:[{H:"span",M:"captions-text"}]});this.B=[];this.J=!1;this.F=a;this.D=[];this.G=[];this.sa=e;this.ra=f;this.C=null;this.V=.96*e;this.fa=.96*f;this.o=k;this.pa=c;this.A=this.va["captions-text"];this.ha=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.L=d/360*16;this.type=R6.yp;this.ca=this.L*Yua(l);a=new g.fG(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.WL,this);a.subscribe("dragmove",this.VL,this);a.subscribe("dragend",this.UL,this);this.ea=this.da=0;a="";this.o.Uj&&(a=L6(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.Uj+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":Zua[this.o.textAlign]};this.ha&&(b["border-radius"]=a?this.ca/
8+"px":"");g.gh(this.element,b);switch(this.o.Pg){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},Yua=function(a){var b=1+.25*(a.Xi||0);
if(a.offset==T6.fv||a.offset==T6.jv)b*=.8;return b},U6=function(a,b){var c={},d=b.background?b.background:a.o.rb.background;
if(null!=b.Xe||b.background){var e=null!=b.Xe?b.Xe:a.o.rb.Xe;d=L6(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ha&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ca/8+"px")}if(null!=b.Xi||null!=b.offset)c["font-size"]=a.L*Yua(b)+"px";d=1;e=b.color||a.o.rb.color;if(b.color||null!=b.Bh)e=L6(e),d=null==b.Bh?a.o.rb.Bh:b.Bh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Rh;f==g.s3.NONE&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+
d+")";b.Vv&&(k=e=b.Vv);var l=a.L/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1),d=[];switch(f){case g.s3.DROP_SHADOW:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case g.s3.RAISED:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case g.s3.DEPRESSED:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case g.s3.rv:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case g.u3.Nu:e=
'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case g.u3.Su:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case g.u3.Mu:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case g.u3.CASUAL:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case g.u3.CURSIVE:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case g.u3.Cp:e=g.$E()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case g.u3.Bu:case g.u3.zp:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.rb.offset);switch(e){case T6.fv:c["vertical-align"]="sub";break;case T6.jv:c["vertical-align"]="super"}b.fontFamily==g.u3.Cp&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Jr&&(c["font-style"]="italic");b.underline&&
(c["text-decoration"]="underline");b.Xq&&(c.visibility="hidden");return c},$ua=function(a,b,c){a.J=a.J||!!c;
var d={};g.Ba(d,a.o.rb);g.Ba(d,c||b.o);g.Ba(d,a.pa.rb);c=a.D[0];if(c&&d.background==c.background&&d.Xe==c.Xe&&!!d.Xq==!!c.Xq&&d.Rh==c.Rh){var e;for(e=0;e<a.D.length;e++)if(Wua(d,a.D[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.ne("SPAN");g.gh(f,U6(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.D.length=e}else a.G.length=0,a.D.length=0,f=g.ne("SPAN"),g.gh(f,U6(a,d)),a.A.appendChild(f);a.C&&a.C.parentNode!=f&&(g.ue(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.B.length||!b.C){if(0<e||0!=a.B.length){var m=g.ne("BR");f.appendChild(m)}f.appendChild(g.oe("\u00a0"));a.C=g.oe("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.oe(l):l,m))}a.D.push(d);a.G.push(f);a.B.push(b)},ava=function(){},W6=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new V6(this);this.D=new V6(this);this.g=[];this.clear()},cva=function(a,b,c){if(255==a&&255==b||!a&&!b)return{sm:a,
tm:b,result:0};a=bva[a];b=bva[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{sm:a,tm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{sm:a,tm:b,result:2};return{sm:a,tm:b,result:3}},eva=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,dva(a.C,b,c,d))},fva=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?eva(a,d.Qv,d.Rv,b):1==d.type&&a.A&496&&dva(a.D,d.Qv,d.Rv,b)}a.g.length=0},X6=function(){this.g=0},Y6=function(){this.o=this.A=this.g=0},Z6=function(){this.timestamp=this.wf=0;
this.g=!1},$6=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new Z6}this.g=this.o=this.Nc=0;this.style=new X6;this.C=a;this.B=0},a7=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.wf){0==c&&(c=m,d=q);var n=String.fromCharCode(r.wf),w=r.timestamp;w<e&&(e=w);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.wf||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.wf,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),w=q.timestamp,w<=e&&(e=w),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},kva=function(a,b){switch(a){case 0:return gva[(b&127)-32];
case 1:return hva[b&15];case 2:return iva[b&31];case 3:return jva[b&31]}return 0},b7=function(a){return a.A[a.Nc][a.o]},c7=function(a,b,c){2<=b&&1<a.o&&(--a.o,b7(a).wf=0);
var d=b7(a);d.timestamp=a.C.o+0;d.wf=kva(b,c);32>a.o&&a.o++},lva=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].Mm(a.A[c+e][f])},d7=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},e7=function(a){a.Nc=0<a.g?a.g:1;
a.o=1;d7(a,0,15)},f7=function(a){this.B=a;
this.C=0;this.style=new X6;this.D=new $6(a);this.F=new $6(a);this.G=new $6(a);this.o=this.D;this.A=this.F;this.g=this.o},g7=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:a7(d,c),e7(a.o),e7(a.A),d.Nc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(a7(d,c),d7(d,d.Nc-d.g,b)):d.Nc<b&&(b=d.g),d.g=b)},mva=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},nva=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},V6=function(a){this.o=a;
this.g=new Y6;this.C=0;this.A=new f7(a);this.D=new f7(a);this.B=this.A},dva=function(a,b,c,d){a.g.update();
b=cva(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.sm;c=b.tm;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&c7(e,0,b),c&96&&c7(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&a7(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Nc;break;case 3:if(d!=c.Nc){if(d<c.g&&(d=c.g,d==c.Nc))break;var f=1+c.Nc-c.g,k=1+d-c.g;lva(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));d7(c,b,e)}}c.Nc=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:c7(b.g,0,32);break a;case 48:57==c?(b=b.g,b7(b).wf=0,32>b.o&&b.o++):c7(b.g,1,c&15)}break;case 2:c&32&&c7(b.g,2,c&31);break;case 3:c&32&&c7(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:mva(b);break;
case 33:b=b.g;1<b.o&&(--b.o,b7(b).wf=0);break;case 36:b=b.g;d=b7(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:g7(b,2,d);break;case 38:g7(b,3,d);break;case 39:g7(b,4,d);break;case 40:c7(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);e7(d);nva(b);break;case 43:nva(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:a7(a,d)}d7(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Nc){++a.Nc;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Nc<a.g&&(a.Nc=a.g));b=a.Nc-a.g+1;a7(a,d);lva(a,b,b+1,a.g-1);d7(a,a.Nc,1)}break;case 46:d7(b.A,0,15);break;case 47:a7(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;mva(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},h7=function(){},i7=function(a){this.A=a;
this.o=null},pva=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?j7.Dp:j7.Ul;a=g.ur("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");ova(d,e,k,b,f,a.firstChild,{},c)},ova=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Jr=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");k7.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new M6(a,b,c,d,n.nodeValue,e||0<m,g.Vb(k)?void 0:k));else{var q={};g.Ba(q,k);ova(a,b,c,d,e||0<m,n,q,l)}}},l7=function(){this.A={};
this.o=null},m7=function(a){this.o={};
this.C={};this.D={};this.A="_"+O6++;this.B=a},n7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},o7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},p7=function(a,b){var c=n7(a,b);
if(void 0!=c)return c},q7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return k7.test(c),c},qva=function(a,b){var c={},d=b.getAttribute("ws");
g.Ba(c,d?a.D[d]:a.B);d=p7(b,"mh");null!=d&&(c.Wr=d);d=p7(b,"ju");null!=d&&(c.textAlign=d);d=p7(b,"pd");null!=d&&(c.Nj=d);d=q7(b,"wfc");null!=d&&(c.windowColor=d);d=n7(b,"wfo");void 0!=d&&(c.Uj=d/255);return c},rva=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ba(c,a.C[d]);d=p7(b,"ap");null!=d&&(c.Pg=d);d=n7(b,"cc");null!=d&&(c.SG=d);d=n7(b,"ah");null!=d&&(c.ni=d);d=n7(b,"rc");null!=d&&(c.xo=d);d=n7(b,"av");null!=d&&(c.Ii=d);return c},sva=function(a,b,c){var d={};
g.Ba(d,rva(a,b));g.Ba(d,qva(a,b));c?Wua(d,a.B)?(c=a.A,d=a.B):c="_"+O6++:c=b.getAttribute("id")||"0";a=n7(b,"t");b=n7(b,"d")||0x8000000000000;return new N6(a,b,0,c,d)},r7=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},s7=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},tva=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},t7=function(a,b){this.B=a;
this.o="CC3"==b.D?4:0;this.A=new W6(!1);this.A.A=1<<this.o},uva=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=tva(a);b.toString(16);if(1380139777!=b)return!1;a.version=s7(a);if(1<a.version)return!1;s7(a);s7(a);s7(a);return!0},vva=function(){this.o=[];
this.g=[]},u7=function(a,b){return b?a.g.concat(a.o):a.g},v7=function(a,b){switch(b.B){case "asr":var c=a.o;
g.ab(c,(0,g.z)(b.J,b))||c.push(b);break;default:c=a.g,g.ab(c,(0,g.z)(b.J,b))||c.push(b)}},w7=function(){this.o=null},wva=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Jr=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new M6(b,c,d,e.id,q.nodeValue,f||0<n,g.Vb(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.Ba(r,l);wva(a,b,c,d,e,!0,q,r,m)}}},x7=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},y7=function(a){g.L.call(this);
this.by=!!a;this.o=new vva;this.C=[];this.g=null},yva=function(a){var b={};
if(a=J6(a))b.lang=a,xva.test(a)&&(b.Nj=Q6.Bp);return b},zva=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new w7),a.g.g(b,d);b=g.ur(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new m7(yva(c)):a.g=new l7:a.g=new i7(yva(c)));return a.g.g(b,d)}try{if(g.u(b))var f=!1;else{var k=new r7(b,0,0);f=uva(k)}if(f)return a.g||(a.g=new t7(e,c)),a.g.g(b,d)}catch(l){g.BE(l)}return[]},z7=function(a){y7.call(this,a.Bm);
this.B=void 0;this.A=null;this.C=a.captionTranslationLanguages},A7=function(){this.qb=[]},B7=function(a,b,c,d,e,f){g.L.call(this);
this.L=a;this.J=b;this.B=new A7;this.g=null;this.D=d;this.I=f;this.o=this.A=null;this.N=c;this.C=e||!1;this.F=new g.Ct(this.vy,1E3,this);g.M(this,this.F);this.G=new g.aG(this);g.M(this,this.G);this.G.R(b,"seekto",this.oz);this.oz(b.getCurrentTime());this.vy()},C7=function(a,b){y7.call(this);
this.D=a;this.T=b;this.A=null;this.B=!1},D7=function(a,b,c,d,e,f){S6.call(this,a,b,c,d,e,f);
this.type=R6.xp},E7=function(a,b,c,d,e,f){S6.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=R6.Ap;this.I=this.N=0;this.O=window.NaN;this.ka=null;this.Y=new g.Ct(this.xQ,433,this);g.M(this,this.Y)},F7=function(a){if(!a.N){var b=g.ne("SPAN");
g.gh(b,U6(a,a.o.rb));a.A.appendChild(b);b.appendChild(g.oe("M"));var c=b.offsetHeight,d=g.ne("BR");b.appendChild(d);b.appendChild(g.oe("M"));a.N=b.offsetHeight-c;a.A.removeChild(b)}return a.N},G7=function(a,b,c,d){y7.call(this,d);
c=c||g.QE(a).hl||"";c=c.split("_").join("-");this.D=g.SE(a,{hl:c});this.B=b;this.F={};this.A=null},K7=function(a){g.WV.call(this,a);
g.bE();this.F=g.X(a);this.o=a.ga();this.ha=g.eV(a);this.T=a;var b=null,c=g.ED("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.sD(c));this.aa=b;this.C={rb:{}};this.G={rb:{}};this.J=[];this.L={};this.V={};this.O=!1;this.ka="1"==this.o.Xb.cc_auto_caps||"1"==this.F.N.cc_auto_caps;c=b=this.A=this.B=this.D=this.I=this.N=this.ea=null;H7(this)||(b=new g.zt(this.qC,void 0,this),g.M(this,b),c=new g.Ct(this.hS,2E3,this),g.M(this,c));this.da=b;this.fa=c;this.Y=new g.aG(this);g.M(this,this.Y);H7(this)||
this.Y.R(a,"resize",this.Lt);this.Y.R(a,"onPlaybackAudioChange",this.ON);this.Y.R(a,"crn_captions",this.FL,this);this.Y.R(a,"crx_captions",this.GL,this);I7(this,J7(this,"display-settings")||{});Ava(this)&&this.load()},H7=function(a){if("3"!=a.F.C)return!1;
a=a.T.app.F;return!(!a||!a.g.textTracks)},Bva=function(a){if(a.o.captionTracks.length)var b=a.g.oh().Nv;
if("FORCED_ON"==b||1==a.F.Tg||1==a.o.Tg||"alwayson"==g.RP(a.o,"yt:cc"))return!0;if(2==a.F.Tg){var c=J7(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.RP(a.o,"yt:cc")},Ava=function(a){return H7(a)?!a.o.Aa:a.o.captionTracks.length&&a.g.oh().tk?!0:Bva(a)},Cva=function(a,b){if(a.B){var c=u7(a.B.o,b||a.ka);
if(a.D&&a.D.g)return a.D.g;if(!a.F.experiments.g("legacy_default_caption_track"))for(var d=[a.o.Sg,a.F.Sg,g.RP(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(J6(c[f])==d[e])return c[f];return a.D&&a.D.mq?a.D.mq:c[0]||a.D&&a.D.tk}return null},L7=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.O=c);a.A=b;a.load(d)},Dva=function(a,b){var c=g.yZ(a.ha,!0).height;
if(!c)return null;var d=a.ha.Wa();switch(null!=b.params.Wr?b.params.Wr:b.params.MS?R6.Ap:1<b.o.length?R6.xp:R6.yp){case R6.xp:return new D7(b,a.C,a.G,c,d.width,d.height);case R6.Ap:return new E7(b,a.C,a.G,c,d.width,d.height);default:return new S6(b,a.C,a.G,c,d.width,d.height)}},I7=function(a,b,c){var d=M7.rb;
a.C={};g.Ba(a.C,M7);a.C.rb={};g.Ba(a.C.rb,d);a.G={rb:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;k7.test(f);e.rb.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;k7.test(f);e.rb.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||M7.windowColor;k7.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.Xe);e.rb.Xe=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;null==f&&(f=d.Xi);e.rb.Xi=f;e=b.textOpacityOverride?
a.G:a.C;f=b.textOpacity;null==f&&(f=d.Bh);e.rb.Bh=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=M7.Uj);e.Uj=f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.Rh);e.rb.Rh=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.rb.fontFamily=f;a.loaded&&a.Lt();c&&N7(a,"display-settings",b)},Fva=function(a,b){if(b&&!a.I){var c=P6({Nj:Q6.wp,
lang:"en"});a.I=[c,new M6(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.rV(a.g,a.I)}else!b&&a.I&&(Eva(a,a.I),a.I=null)},Eva=function(a,b){g.tV(a.g,b);
(0,g.H)(b,function(a){g.nb(this.J,a)},a);
a.da.Bk()},Gva=function(a,b){return a&&g.u(a)&&k7.test(a)?a:b},Hva=function(a,b){return g.qa(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Jva=function(a,b){if(a&&g.u(a)){var c=Iva.indexOf(a);
return-1!=c?c:b}return b},Lva=function(a,b){if(a&&g.u(a)){var c=Kva.indexOf(a);
return-1!=c?c:b}return b},Mva=function(a,b){return g.qa(a)&&!(0,window.isNaN)(a)?g.Md(a,-2,4):b},J7=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},N7=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.EJ.prototype.nn=I6(2,function(a){return(a=this.Wh(a))?a.o:0});
g.cM.prototype.nn=I6(1,function(){return 0});
g.BI.prototype.J=I6(0,function(a){return a?this.toString()==a.toString():!1});
var Uua=/^#(?:[0-9a-f]{3}){1,2}$/i,Vua=/#(.)(.)(.)/,xva=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,T6={fv:0,NORMAL:1,jv:2},Kva="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Iva=["none","raised","depressed","uniform","dropShadow"],k7=/^#(?:[0-9a-f]{3}){1,2}$/i;var O7={Ju:0,E_:1,XD:2},Zua=["left","right","center"],Q6={wp:0,Bp:1,y0:2,CV:3},j7={U1:0,Ul:5,Dp:6},R6={yp:0,xp:1,Ap:2};var M7={windowColor:g.t3.mp,Uj:0,textAlign:O7.XD,Pg:7,ni:50,Ii:100,rb:{background:g.t3.mp,Xe:.75,Rh:g.s3.NONE,color:g.t3.Fp,fontFamily:g.u3.zp,Xi:0,Bh:1,offset:T6.NORMAL}};g.p(M6,g.BJ);M6.prototype.toString=function(){return g.BJ.prototype.toString.call(this)};g.p(N6,g.BJ);N6.prototype.toString=function(){return g.BJ.prototype.toString.call(this)};
var O6=0;g.p(S6,g.Y);g.h=S6.prototype;g.h.WL=function(a,b){var c=g.wh(this.element,this.element.parentElement);this.da=a-c.x;this.ea=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.VL=function(a,b){var c=g.zh(this.element),d=a-this.da-.02*this.sa,e=b-this.ea-.02*this.ra,f=(d+c.width/2)/this.V*3,f=Math.floor(g.Md(f,0,2)),k=(e+c.height/2)/this.fa*3,k=Math.floor(g.Md(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.V,d=100*g.Md(d,0,1),c=(e+k/2*c.height)/this.fa,c=100*g.Md(c,0,1);this.F.params.Pg=l;this.F.params.Ii=c;this.F.params.ni=d;this.o.Pg=l;this.o.Ii=c;this.o.ni=d;this.AB()};
g.h.UL=function(){g.Rp(this.element,"ytp-dragging")};
g.h.AB=function(){this.Fi(this.B)};
g.h.Yb=function(){return this.type};
g.h.Fi=function(a){var b=Math.min(this.Ww(),this.V),c=this.Vw();g.gh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.Rp(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":""};var d=.96*this.o.ni+2,e=this.o.Pg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.o.Ii+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.A.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.gh(this.element,a)};
g.h.Rp=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.J||this.B.length>b)b=0,this.J=!1,this.B=[],this.D=[],this.G=[],this.C=null,g.re(this.A);for(;b<a.length;b++)$ua(this,a[b])};
g.h.Ww=function(){return 0};
g.h.Vw=function(){return 0};
g.h.toString=function(){return g.Y.prototype.toString.call(this)};ava.prototype.B=function(){};W6.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
W6.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var bva=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];X6.prototype.set=function(a){this.g=a};
X6.prototype.get=function(){return this.g};
Y6.prototype.clear=function(){this.g=0};
Y6.prototype.update=function(){this.g=2==this.g?1:0};
Y6.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
Z6.prototype.Mm=function(a){this.wf=a.wf;this.timestamp=a.timestamp;this.g=a.g};
Z6.prototype.reset=function(){this.timestamp=this.wf=0;this.g=!1};
$6.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Nc=1};
var gva=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],hva=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],iva=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],jva=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];f7.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
V6.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};h7.prototype.reset=function(){};g.p(i7,h7);i7.prototype.g=function(a){var b=[];this.o||(this.o=P6(this.A),b.push(this.o));a=g.ma(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())pva(c.value,this.o.id,b);return b};g.p(l7,h7);
l7.prototype.g=function(a){var b=[];this.o||(this.o=P6(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=P6());
var k={};f&&(g.Ba(k,f.params),f=f.params.rb)&&(k.rb={},g.Ba(k.rb,f));e.getAttribute("rc")&&(k.xo=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.SG=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Pg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.ni=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Ii=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Nj=Q6.Bp,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Nj=Q6.wp));e.getAttribute("bc")&&(k.rb||(k.rb={}),k.rb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.rb||(k.rb={}),k.rb.Xe=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.rb||(k.rb={}),k.rb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.MS=(0,window.parseInt)(e.getAttribute("sd"),10));
f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new N6(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],pva(a,this.o.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(m7,h7);
m7.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.ma(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())switch(b=b.value,b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.ma(c.childNodes),a=c.next();!a.done;a=c.next())switch(a=a.value,a.tagName){case "pen":var b=a.getAttribute("id"),e=this.o,f={},k=a.getAttribute("p");k&&g.Ba(f,this.o[k]);k=o7(a,"b");null!=k&&(f.bold=k);k=o7(a,"i");null!=k&&(f.Jr=k);k=o7(a,"u");null!=k&&(f.underline=k);k=p7(a,"et");
null!=k&&(f.Rh=k);k=p7(a,"of");null!=k&&(f.offset=k);k=q7(a,"bc");null!=k&&(f.background=k);k=q7(a,"ec");null!=k&&(f.Vv=k);k=q7(a,"fc");null!=k&&(f.color=k);k=p7(a,"fs");void 0!=k&&k!=g.u3.Bu&&(f.fontFamily=k);k=n7(a,"sz");void 0!=k&&(f.Xi=k/100-1);k=n7(a,"bo");void 0!=k&&(f.Xe=k/255);a=n7(a,"fo");void 0!=a&&(f.Bh=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.D[b]=qva(this,a);break;case "wp":b=a.getAttribute("id"),this.C[b]=rva(this,a)}c=[];if(d){a={};var b=void 0;d=g.ma(d.childNodes);
for(e=d.next();!e.done;e=d.next())switch(e=e.value,e.tagName){case "w":var l=sva(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=Ke,f=[],k=e.getAttribute("w")||this.A,q=!!o7(e,"a"),r=n7(e,"t")||0,w=n7(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);for(var m=q?j7.Dp:j7.Ul,n=this.o[e.getAttribute("p")],A=e.childNodes,D=0;D<A.length;D++){var B=A[D];0<D&&(q=!0);if("s"==B.tagName)var Q=B,B=r,ba=w,Wa=k,ob=q,la=m,bg=Q.textContent?Q.textContent:
"",db=this.o[Q.getAttribute("p")],Q=n7(Q,"t")||0,B=new M6(B+Q,ba-Q,la,Wa,bg,ob,db);else B=new M6(r,w,m,k,B.textContent||"",q,n);f.push(B)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var Ke=null!=e.getAttribute("d");f[0].windowId==this.A&&(l=sva(this,e,!0),c.push(l));e=g.ma(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.o.push(f),c.push(f)}}}return c};g.p(r7,ava);r7.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+O6++;c=c/1E3-this.F;d=d/1E3-this.F;var k=j7.Ul;a=new N6(c,d-c,k,f,{textAlign:O7.Ju,Pg:0,ni:2.5*b,Ii:5.33*a});e=new M6(c,d-c,k,f,e);this.A.push(a);this.A.push(e)}};
g.p(t7,h7);t7.prototype.g=function(a){a=new r7(a,0,this.B);if(uva(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=tva(a)*(1E3/45)),a.C=s7(a);0<a.C;a.C--){var b=s7(a),c=s7(a),d=s7(a);b&4&&(b&3)==this.o&&(0==this.o||1==this.o)&&(b=this.A,b.g.push({time:a.D,type:this.o,Qv:c,Rv:d,order:b.g.length}))}fva(this.A,a);return a.A}return[]};
t7.prototype.reset=function(){this.A.clear()};g.p(w7,h7);
w7.prototype.g=function(a,b){for(var c=[],d=a.split(Nva),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Ova.test(f)){var l=P7.exec(f);if(l&&3<=l.length){var m=x7(l[1]),l=x7(l[2])-m,m=m+k,f=f.substring(P7.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");P7.lastIndex=0;var n=f,f={};this.o||(this.o=P6({Wr:R6.yp}),c.push(this.o));var q=this.o,k=j7.Ul;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new M6(m,l,k,q.id,n,!1,g.Vb(f)?void 0:f));else{n=n.split(Pva);1!=n.length&&(k=j7.Dp,q="_"+Qva++,q=new N6(m,l,k,
q,{}),c.push(q));for(var r=m,w=0;w<n.length;w++){var A=n[w];if(0==w%2){var D=g.ur("<html>"+A+"</html>");if(D.getElementsByTagName("parsererror").length){var B=D.createElement("span");B.appendChild(D.createTextNode(A))}else B=D.firstChild;wva(this,r,l-(r-m),k,q,0<w,B,f,c)}else r=x7(A)}}}P7.lastIndex=0}}return c};
var Qva=0,Ova=/^NOTE/,Nva=/(?:\r\n|\r|\n){2,}/,P7=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),Pva=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(y7,g.L);y7.prototype.Hd=function(){this.g=null};
y7.prototype.W=function(){g.L.prototype.W.call(this);this.Hd()};
y7.prototype.lB=function(){return!1};g.p(z7,y7);g.h=z7.prototype;g.h.Qr=function(a,b){var c=this.zk(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Hd();this.A=g.WE(c,{format:"RAW",Vb:d,withCredentials:!0})};
g.h.Rr=function(a,b,c,d){this.B=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())v7(this.o,c.value);a()};
g.h.zk=function(a){var b=a.I,c={};if(this.B||a.A)c.fmt=this.B||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.SE(b,c)};
g.h.Hd=function(){y7.prototype.Hd.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Hd();y7.prototype.W.call(this)};A7.prototype.contains=function(a){a=g.yb(this.qb,a);return 0<=a||0>a&&1==(-a-1)%2};
A7.prototype.length=function(){return this.qb.length/2};g.p(B7,g.L);g.h=B7.prototype;g.h.W=function(){g.L.prototype.W.call(this);this.o&&this.o.abort()};
g.h.oz=function(a){var b=this.g;this.g=g.Za(this.N.Zg(a).g);b!=this.g&&this.I&&this.I()};
g.h.reset=function(){this.B=new A7;this.o&&(this.o.abort(),this.o=null)};
g.h.vy=function(){var a;if(a=null!==this.g)a=this.g,a=a.na.xi(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.J.getCurrentTime())){a=this.g;a=a.na.Xk(a);if(!this.B.contains(a.g[0].za)){var b=g.KL(g.OL(a,this.L,{})),c={format:"RAW",Ed:(0,g.z)(this.tQ,this),withCredentials:!0};this.C&&(c.responseType="arraybuffer");this.o=g.WE(b,c);this.A=a;var b=this.B,c=this.A.g[0].za,d=g.yb(b.qb,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.qb[d-1]&&d<b.qb.length&&1==b.qb[d]-c?(g.kb(b.qb,d),g.kb(b.qb,d-1)):
0<d&&1==c-b.qb[d-1]?b.qb[d-1]=c:d<b.qb.length&&1==b.qb[d]-c?b.qb[d]=c:(g.ub(b.qb,d,0,c),g.ub(b.qb,d+1,0,c)))}this.g=g.Za(a.g)}this.F.start()};
g.h.tQ=function(a){(this.C?!a.response:!a.responseText)||400<=a.status||null===this.D||(this.C?this.D(a.response,1E3*this.A.g[0].startTime):this.D(a.responseText,1E3*this.A.g[0].startTime));this.o=this.A=null};g.p(C7,y7);g.h=C7.prototype;g.h.Qr=function(a,b){this.Hd();var c=this.D.g[a.o];if(c){var d=1E3*c.index.nn(c.index.tg()),e=g.X(this.T).Jd;this.A=new B7(new g.OK,this.T,c,function(c,e){b(c,a,e,d)},e,(0,g.z)(function(){e&&(this.A&&this.A.reset(),this.g&&this.g.reset(),this.B=!0)},this))}};
g.h.lB=function(){var a=this.B;this.B=!1;return a};
g.h.Rr=function(a){g.X(this.T).Jd?(v7(this.o,new g.BI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),v7(this.o,new g.BI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):v7(this.o,new g.BI({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Hd=function(){y7.prototype.Hd.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.zk=function(){return""};
g.h.W=function(){this.Hd();y7.prototype.W.call(this)};g.p(D7,S6);D7.prototype.Rp=function(a){var b=this.F.o;S6.prototype.Rp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ba(d,c.o);g.Ba(d,Rva);var e=c.o;var f=d}$ua(this,c,d)}};
var Rva={Xq:!0};g.p(E7,S6);g.h=E7.prototype;g.h.AB=function(){g.Dt(this.Y)};
g.h.xQ=function(){g.Rp(this.element,"ytp-rollup-mode");this.Fi(this.ka,!0)};
g.h.Ww=function(){return this.I};
g.h.Vw=function(){return this.F.params.xo*F7(this)};
g.h.Fi=function(a,b){this.ka=a;if(F7(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=this.I;this.I=0;S6.prototype.Fi.call(this,a);this.I=Math.max(c,this.A.offsetWidth+1);c=this.F.params.xo*F7(this)-this.A.offsetHeight;c!=this.O&&(b||(0,window.isNaN)(this.O)||(g.S(this.element,"ytp-rollup-mode"),this.Y.Pd()),g.gh(this.A,"transform",c?"translateY("+c+"px)":""),this.O=c);S6.prototype.Fi.call(this,a)}else S6.prototype.Fi.call(this,
a)};g.p(G7,y7);g.h=G7.prototype;g.h.Qr=function(a,b){var c=this.zk(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Hd();this.A=g.WE(c,{format:"RAW",Vb:d,withCredentials:!0})};
g.h.Rr=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.B,fmts:Number(b||!1),vssids:1};this.by&&(b.asrs=1);d=g.SE(d,b);b=(0,g.z)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.o,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value,l=m.getAttribute("formats"),n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),w=m.getAttribute("kind"),A=m.getAttribute("id"),D="true"==m.getAttribute("cantran"),
m=m.getAttribute("vss_id");v7(d,new g.BI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:w,id:A,is_servable:!0,is_translateable:D,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.F[l.languageCode]=l.languageName,this.C.push(new g.AI(l))}a()},this);
this.Hd();this.A=g.WE(d,{format:"RAW",Vb:b,withCredentials:!0})};
g.h.zk=function(a){var b=this.D,c={v:this.B,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=J6(a));return b=g.SE(b,c)};
g.h.Hd=function(){y7.prototype.Hd.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Hd();y7.prototype.W.call(this)};g.p(K7,g.WV);g.h=K7.prototype;g.h.W=function(){H7(this)||Fva(this,!1);g.WV.prototype.W.call(this)};
g.h.load=function(a){g.WV.prototype.load.call(this);this.D=this.g.oh();if(this.B||a)this.A?(a?this.UA(a,this.A):3!=this.g.Ya()&&this.B.Qr(this.A,(0,g.z)(this.UA,this)),this.g.xa("captionschanged",K6(this.A))):this.g.xa("onCaptionsTrackListChanged");else{var b;a=this.o;a.Aa||g.X(this.T).Jd&&null!=a.ua&&null!=a.ua.g.rawcc?b=new C7(this.o.ua,this.g):this.o.captionTracks.length?b=new z7(this.o):b=new G7(this.o.Cm,this.o.videoId,this.o.Sg||this.F.Sg||g.RP(this.o,"yt:cc_default_lang")||this.F.Ma,this.o.Bm);
this.B=b;b.Rr((0,g.z)(this.ZQ,this),!0,H7(this)?"vtt":void 0,this.g.oh())}};
g.h.unload=function(){if(H7(this))for(var a=g.$d(window.document,"track",void 0,this.T.app.F.g),b=0;b<a.length;b++)g.ue(a[b]);else g.Et(this.fa),g.uV(this.g,"captions"),this.J=[],this.B&&this.B.Hd(),this.I&&g.rV(this.g,this.I),this.Lt();g.WV.prototype.unload.call(this);(a=g.cV(this.g.app))&&a.D&&g.eQ(a.D.A);this.g.xa("captionschanged",{})};
g.h.ZQ=function(){if(this.O||Bva(this))var a=Cva(this,this.O);if(H7(this))for(var b=u7(this.B.o,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.CI(d),srclang:J6(d),src:this.B.zk(d)};d==a&&(e["default"]=1);for(var d=this.T.app.F,e=[g.ke("TRACK",e)],f=0;f<e.length;f++)d.g.appendChild(e[f])}else!this.A&&a&&L7(this,a),this.g.xa("onCaptionsTrackListChanged"),this.g.xa("onApiChange")};
g.h.bT=function(){this.loaded&&!H7(this)&&this.unload()};
g.h.UA=function(a,b,c,d){if(a){this.B.lB()&&(this.J=[],g.uV(this.T,"captions"),this.da.Bk());a=zva(this.B,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:J6(b)};b.g&&(c.fromLangCode=b.o);g.lV(this.g,"cc",c);if(this.A!=(this.D&&this.D.tk)){if(this.O&&!g.ON(this.F)&&!g.PN(this.F)){g.Et(this.fa);b=P6({Pg:0,ni:5,Ii:5,xo:2,textAlign:O7.Ju,Nj:Q6.wp,lang:"en"});this.N=[b];c=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.ea||(d=new g.FV(g.uE()),g.M(this,d),this.ea=d.element);d=b.end-b.start;
var e=g.CI(this.A);e&&this.N.push(new M6(b.start,d,0,b.id,e));this.N.push(new M6(b.start,d,0,b.id,c[0]),new M6(b.start,d,0,b.id,this.ea,!0),new M6(b.start,d,0,b.id,c[1],!0));g.rV(this.g,this.N);this.fa.Pd()}if(this.O||g.ON(this.F))N7(this,"module-enabled",!0),this.D&&(this.D.g=this.A);(b=g.cV(this.g.app))&&b.D&&g.eQ(b.D.A)}g.rV(this.g,a);this.O=!1}};
g.h.FL=function(a){this.J.push(a);this.da.Bk()};
g.h.GL=function(a){g.nb(this.J,a);this.da.Bk()};
g.h.SR=function(a){if(a instanceof N6){var b=this.L[a.id];b&&b.F!=a&&(b.dispose(),delete this.L[a.id],b=null);b||(b=Dva(this,a))&&(this.L[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.hS=function(){Eva(this,this.N);this.N=null};
g.h.qC=function(){this.da.stop();Xua(this.V);this.J.sort(g.CJ);var a=this.J;if(this.I){var b=(0,g.we)(a,function(a){return-1==this.I.indexOf(a)},this);
b.length&&(a=b)}(0,g.H)(a,this.SR,this);g.Kb(this.L,function(a,b){this.V[b]?(a.element.parentNode||g.yV(this.g,a.element,4),a.Fi(this.V[b])):(a.dispose(),delete this.L[b])},this)};
g.h.zB=function(){I7(this,{},!0)};
g.h.Fq=function(){var a=M7.rb,a={background:a.background,backgroundOpacity:a.Xe,charEdgeStyle:a.Rh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Xi,textOpacity:a.Bh,windowColor:M7.windowColor,windowOpacity:M7.Uj},b=J7(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Ot=function(a,b){var c={};g.Ba(c,J7(this,"display-settings"));g.Ba(c,a);I7(this,c,b);this.g.X("captionssettingschanged")};
g.h.Lt=function(){!H7(this)&&this.loaded&&(g.Kb(this.L,function(a,b){a.dispose();delete this.L[b]},this),this.qC())};
g.h.os=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Md(b,-2,4);this.Ot({fontSizeIncrement:c});return c;case "reload":b&&!H7(this)&&L7(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.F.Gb&&N7(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(H7(this))break;if(!g.xa(b))break;if(g.Vb(b)){L7(this,null,!0);break}for(var d=u7(this.B.o,!0),e=0;e<d.length;e++){var f=d[e];f.o!=b.languageCode||c&&f.D!=b.languageName||(c=b.translationLanguage?
Tua(f,b.translationLanguage):f)}!c||c==this.A&&this.loaded||L7(this,c,!0)}else return this.loaded&&this.A&&this.A!=(this.D&&this.D.tk)?K6(this.A):{};return"";case "tracklist":return this.B?(0,g.I)(u7(this.B.o,b&&b.includeAsr),function(a){return K6(a)}):[];
case "translationLanguages":return this.B?this.B.C:[];case "displaySettings":c=this.Fq();if(g.ON(this.F)&&b&&g.xa(b))if(b.reset)this.zB();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=Gva(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=Hva(b[d],c[d]);break;case "charEdgeStyle":f[d]=Jva(b[d],c[d]);break;case "fontSizeIncrement":f[d]=Mva(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=Lva(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Ot(f,!0);c=this.Fq()}c.fontFamilyOption=Kva[c.fontFamily];c.charEdgeStyle=Iva[c.charEdgeStyle];return c;case "sampleSubtitles":H7(this)||void 0==b||Fva(this,!!b);break;case "xmlTrack":b&&this.F.Gb&&(H7(this)||L7(this,new g.BI({languageName:b.name}),!1,b.xml))}};
g.h.CL=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.F.Gb&&a.push("stickyLoading","xmlTrack");return a};
g.h.DL=function(){var a=this.A;return a?{cc:a.F}:{}};
g.h.oC=function(){this.loaded&&this.A?(N7(this,"module-enabled",!1),this.unload()):L7(this,this.A||Cva(this,!0),!0)};
g.h.ON=function(){this.o.captionTracks.length&&(this.loaded&&this.unload(),Ava(this)&&this.load())};g.oZ.captions=K7;})(_yt_player);
